// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PilotsRUs.User.App.Data;

#nullable disable

namespace PilotsRUs.User.App.Data.Migrations
{
    [DbContext(typeof(UserAppDbContext))]
    [Migration("20260716072932_AddFlightAssignments")]
    partial class AddFlightAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("PilotsRUs.User.App.Data.FlightAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AircraftRegistrationNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("ArrivalAirportIcaoCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("AssignedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("AssignedCargoKg")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedPassengersBusiness")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedPassengersEconomy")
                        .HasColumnType("INTEGER");

                    b.Property<int>("AssignedPassengersFirst")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DepartureAirportIcaoCode")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("FlightDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlightNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ScheduleId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("FlightAssignments");
                });
#pragma warning restore 612, 618
        }
    }
}
