using Microsoft.EntityFrameworkCore;
using PilotsRUs.API.WebApi.Data;
using PilotsRUs.Shared.SDK.Schedules;

namespace PilotsRUs.API.WebApi.Features.Schedules;

public static class ScheduleEndpoints
{
    public static IEndpointRouteBuilder MapScheduleEndpoints(this IEndpointRouteBuilder app)
    {
        // No policy name - same as every other domain entity, any authenticated user can view schedules.
        // Read-only: Schedule rows are system-generated by ScheduleGenerator, not admin-authored, so there
        // is no Create/Update/Delete here.
        var group = app.MapGroup("/schedules").RequireAuthorization();

        group.MapGet("/", async (IDbContextFactory<ApplicationDbContext> dbContextFactory) =>
        {
            await using var dbContext = await dbContextFactory.CreateDbContextAsync();
            var schedules = await dbContext.Schedules
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.DepartureAirport)
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.ArrivalAirport)
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.Aircraft)
                .OrderBy(s => s.FlightDate).ThenBy(s => s.ScheduleTemplate.FlightNumber)
                .ToListAsync();
            return Results.Ok(schedules.Select(ToResponse));
        }).WithName("GetSchedules");

        group.MapGet("/{id:guid}", async (Guid id, IDbContextFactory<ApplicationDbContext> dbContextFactory) =>
        {
            await using var dbContext = await dbContextFactory.CreateDbContextAsync();
            var schedule = await dbContext.Schedules
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.DepartureAirport)
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.ArrivalAirport)
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.Aircraft)
                .FirstOrDefaultAsync(s => s.Id == id);
            return schedule is null ? Results.NotFound() : Results.Ok(ToResponse(schedule));
        }).WithName("GetScheduleById");

        return app;
    }

    private static ScheduleResponse ToResponse(Schedule schedule) => new(
        schedule.Id, schedule.ScheduleTemplateId, schedule.FlightDate,
        schedule.ScheduleTemplate.FlightNumber,
        schedule.ScheduleTemplate.DepartureAirport.IcaoCode, schedule.ScheduleTemplate.DepartureAirport.Name,
        schedule.ScheduleTemplate.ArrivalAirport.IcaoCode, schedule.ScheduleTemplate.ArrivalAirport.Name,
        schedule.ScheduleTemplate.Aircraft.RegistrationNumber);
}
