using Microsoft.EntityFrameworkCore;
using PilotsRUs.API.WebApi.Data;
using PilotsRUs.Shared.SDK.Schedules;

namespace PilotsRUs.API.WebApi.Features.Schedules;

public static class ScheduleEndpoints
{
    public static IEndpointRouteBuilder MapScheduleEndpoints(this IEndpointRouteBuilder app)
    {
        // "AccountOrAdmin", not the bare .RequireAuthorization() every other domain entity uses - both
        // Admin.App (Pages/Schedules/Index.cshtml.cs, Admin-audience token) and User.App (flight search,
        // Account-audience token) call this endpoint, and the default scheme alone only accepts Admin
        // tokens. Read-only: Schedule rows are system-generated by ScheduleGenerator, not admin-authored, so
        // there is no Create/Update/Delete here.
        var group = app.MapGroup("/schedules").RequireAuthorization("AccountOrAdmin");

        group.MapGet("/", async (
            string? departureIcao,
            string? arrivalIcao,
            int? minDistanceNauticalMiles,
            int? maxDistanceNauticalMiles,
            int? minFlightTimeMinutes,
            int? maxFlightTimeMinutes,
            IDbContextFactory<ApplicationDbContext> dbContextFactory) =>
        {
            await using var dbContext = await dbContextFactory.CreateDbContextAsync();
            var query = dbContext.Schedules
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.DepartureAirport)
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.ArrivalAirport)
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.Aircraft)
                .AsQueryable();

            if (!string.IsNullOrWhiteSpace(departureIcao))
            {
                var icao = departureIcao.ToUpperInvariant();
                query = query.Where(s => s.ScheduleTemplate.DepartureAirport.IcaoCode == icao);
            }

            if (!string.IsNullOrWhiteSpace(arrivalIcao))
            {
                var icao = arrivalIcao.ToUpperInvariant();
                query = query.Where(s => s.ScheduleTemplate.ArrivalAirport.IcaoCode == icao);
            }

            if (minDistanceNauticalMiles.HasValue)
            {
                query = query.Where(s => s.ScheduleTemplate.DistanceNauticalMiles >= minDistanceNauticalMiles.Value);
            }

            if (maxDistanceNauticalMiles.HasValue)
            {
                query = query.Where(s => s.ScheduleTemplate.DistanceNauticalMiles <= maxDistanceNauticalMiles.Value);
            }

            if (minFlightTimeMinutes.HasValue)
            {
                var minFlightTime = TimeSpan.FromMinutes(minFlightTimeMinutes.Value);
                query = query.Where(s => s.ScheduleTemplate.FlightTime >= minFlightTime);
            }

            if (maxFlightTimeMinutes.HasValue)
            {
                var maxFlightTime = TimeSpan.FromMinutes(maxFlightTimeMinutes.Value);
                query = query.Where(s => s.ScheduleTemplate.FlightTime <= maxFlightTime);
            }

            var schedules = await query
                .OrderBy(s => s.FlightDate).ThenBy(s => s.ScheduleTemplate.FlightNumber)
                .ToListAsync();
            return Results.Ok(schedules.Select(ToResponse));
        }).WithName("GetSchedules");

        group.MapGet("/{id:guid}", async (Guid id, IDbContextFactory<ApplicationDbContext> dbContextFactory) =>
        {
            await using var dbContext = await dbContextFactory.CreateDbContextAsync();
            var schedule = await dbContext.Schedules
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.DepartureAirport)
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.ArrivalAirport)
                .Include(s => s.ScheduleTemplate).ThenInclude(t => t.Aircraft)
                .FirstOrDefaultAsync(s => s.Id == id);
            return schedule is null ? Results.NotFound() : Results.Ok(ToResponse(schedule));
        }).WithName("GetScheduleById");

        return app;
    }

    private static ScheduleResponse ToResponse(Schedule schedule) => new(
        schedule.Id, schedule.ScheduleTemplateId, schedule.FlightDate,
        schedule.ScheduleTemplate.FlightNumber,
        schedule.ScheduleTemplate.DepartureAirport.IcaoCode, schedule.ScheduleTemplate.DepartureAirport.Name,
        schedule.ScheduleTemplate.ArrivalAirport.IcaoCode, schedule.ScheduleTemplate.ArrivalAirport.Name,
        schedule.ScheduleTemplate.Aircraft.Id, schedule.ScheduleTemplate.Aircraft.RegistrationNumber,
        schedule.ScheduleTemplate.DistanceNauticalMiles, schedule.ScheduleTemplate.FlightTime,
        schedule.ScheduleTemplate.Aircraft.PassengerCapacityEconomy,
        schedule.ScheduleTemplate.Aircraft.PassengerCapacityBusiness,
        schedule.ScheduleTemplate.Aircraft.PassengerCapacityFirst,
        schedule.ScheduleTemplate.Aircraft.CargoCapacityKg);
}
